---
- name: Ensure lighthouse directory exists
  file:
      path: ~/{{ working_dir }}
      state: directory
      mode: "0755"

- name: Close any existing compose stack
  command: docker compose -f ~/{{ working_dir }}/docker-compose.yml down
  ignore_errors: true

- name: Render Docker Compose file from Ansible template
  template:
      src: docker-compose.yml.j2
      dest: ~/{{ working_dir }}/docker-compose.yml

- name: Start Docker Compose stack
  command: docker compose -f ~/{{ working_dir }}/docker-compose.yml up --force-recreate -d
