name: "Load SOPS Secrets"
description: "Decrypt secrets for this job"

inputs:
  age_key:
    description: "AGE private key for SOPS"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup SOPS
      uses: nhedger/setup-sops@v2

    - name: Decrypt and export secrets
      shell: bash
      env:
        SOPS_AGE_KEY: ${{ inputs.age_key }}
      run: |
        sops -d --output-type dotenv secrets/secrets.yaml >> $GITHUB_ENV
        sops -d secrets/firebase.json > secrets/.firebase.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=secrets/.firebase.json" >> $GITHUB_ENV