name: Build

on:
    release:
        types: [published]

env:
    REGISTRY: ghcr.io
    REGISTRY_PATH: ghcr.io/skylock-ai/arianrhod
    IMAGE_NAME: arianrhod

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # https://github.com/docker/login-action
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # https://github.com/docker/build-push-action
            - name: Build, tag, and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: |
                      ${{ env.REGISTRY_PATH }}:latest
                      ${{ env.REGISTRY_PATH }}:${{ github.ref_name }}
                  build-args: RELEASE_NAME=${{ github.ref_name }}
                  context: .
